THREAD_COUNT = 700
#THREAD_LENGTH_CM = 213
THREAD_LENGTH_CM = 500

WINDOW_WIDTH = THREAD_COUNT * 1.1
WINDOW_HEIGHT = 550
WINDOW_PADDING_PERCENT = .03

CANVAS_CONTROLS_WEIGHT_PERCENT = .20
CANVAS_CONTROLS_HEIGHT = WINDOW_HEIGHT * CANVAS_CONTROLS_WEIGHT_PERCENT
CANVAS_CONTROLS_WIDTH = WINDOW_WIDTH * (1 - WINDOW_PADDING_PERCENT * 2)

CANVAS_CHINCHORRO_HEIGHT = WINDOW_HEIGHT * (1 - CANVAS_CONTROLS_WEIGHT_PERCENT)
CANVAS_CHINCHORRO_WIDTH = WINDOW_HEIGHT * (1 - WINDOW_PADDING_PERCENT * 2)

GRADIENT_AMT = 50
GRADIENT_POS = 50
GRADIENT_FULL_PERCENT = .5
